Solve issues #236, #239, #240, #241 and #242
KGQA/leaderboard pull request #266
Opened 2024-06-20 11:34 UTC by DavidBlavid

Issues: https://github.com/KGQA/leaderboard/issues/236, https://github.com/KGQA/leaderboard/issues/239, https://github.com/KGQA/leaderboard/issues/240, https://github.com/KGQA/leaderboard/issues/241, https://github.com/KGQA/leaderboard/issues/242

2024-06-21 14:58 UTC, xixi019 requested changes

2024-06-21 14:58 UTC, xixi019 commented on wikidata/CronQuestions.md
TSQA-> TSQR

2024-06-21 14:58 UTC, xixi019 commented on systems.md
TSQA-> TSQR

2024-06-21 14:58 UTC, xixi019 commented on freebase/ComplexWebQuestions.md
add dataset Cr-lt-kgqa and its leaderboard mentioned in the paper: https://arxiv.org/pdf/2405.13873

2024-06-24 08:15 UTC, DavidBlavid commented on wikidata/CronQuestions.md
I assume this is a typo, the original authors call their system TSQA. I would leave it as TSQA.
See here: https://arxiv.org/pdf/2203.00255

2024-06-24 19:29 UTC, xixi019 approved these changes

2024-06-24 19:29 UTC, merged